### ISSUE TITLE
"No input data" message spamming the log

### ISSUE THREAD

**Issue by jamesobutler** [lassoan/SlicerSegmentEditorExtraEffects#11]
Using Slicer 4.10 and the MRHead.nrrd data set, if I place fiducials for "Draw Tube" or "Surface Cut" effect then "No input data" messages will be printed to the log upon adding fiducials. The messages will also be printed to the log when mouse scrolling to another slice in the volume.

It seems like the "No input data" messages originates from [vtkTransformPolyDataFilter](https://github.com/Kitware/VTK/blob/ec5e30cab15537cee62e5db9ee91b65a50d391fd/Filters/General/vtkTransformPolyDataFilter.cxx#L85) which is used in "Draw Tube" and "Surface Cut". 

The output message is also reminiscent of what was described in https://github.com/Slicer/Slicer/pull/563.

**Comment by jamesobutler** [comment]
@lassoan Do you know what the correct course of action is to address this?

**Comment by jamesobutler** [comment]
@lassoan Have you observed all these VTK errors in the Slicer log when using these effects?  I'm not sure if a solution would be within this repo or if should be addressed within Slicer.

**Comment by lassoan** [comment]
Probably the warnings can be solved either in this or in MarkupsToModel repository.

**Comment by jamesobutler** [comment]
Closing this issue as a workaround was committed to the Slicer repo as https://github.com/Slicer/Slicer/commit/724ed0fb8ff9b9fce1dad4c73ed0ece495a63870.
