### ISSUE TITLE
Missing model creation for surface cut and draw tube effects

### ISSUE THREAD

**Issue by jamesobutler** [lassoan/SlicerSegmentEditorExtraEffects#18]
I think the updates to the new markups framework has caused some error. When placing points for the surface cut and draw tube effect while testing with today's Slicer nightly build, there isn't a model being created.  There is just floating fiducial points.  When placing points within the MarkupsToModel module, model creation does work.

**Comment by lassoan** [comment]
I've fixed this in MarkupsToModel a couple of days ago. Are you sure you are using the latest master version?

**Comment by jamesobutler** [comment]
Yes, I installed this extension from ExtensionManager today and it installed the MarkupsToModel dependency. Below is an image of floating fiducial points without a model and the revision of MarkupsToModel printed to the console.  The model gets generated if I toggle the interpolation radio button option for DrawTube here. 
![no-model-generated](https://user-images.githubusercontent.com/15837524/54568520-d8624700-49ad-11e9-987c-07a6b958fd13.png)

**Comment by lassoan** [comment]
Thanks for testing. I've fixed the issues: https://github.com/lassoan/SlicerSegmentEditorExtraEffects/commit/15dfd8a92aa3e55de79eff04313e7eaffe3afe7e

**Comment by jamesobutler** [comment]
I've tested and confirmed the fix works. Thanks!
