### ISSUE TITLE
Add binary mask creation option for Mask volume effect

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerSegmentEditorExtraEffects#2]
For registration, MRI bias field correction, etc. a binary labelmap input is required. Although the selected segment can be exported to a binary labelmap, it would be slightly more convenient to be able to create a binary labelmap directly from the Mask volume effect.

- It would be a third option (in addition to Fill inside and Fill outside).
- The user could specify what values to fill inside and outside. These values should be saved in a separate effect parameter from the "Fill value" so that setting them would not interfere with the regular Fill value(could be "BinaryMaskFillValueInside" = 1 by default; "BinaryMaskFillValueOutside" = 0 by default ).
- Make the output node type a vtkMRMLLabelMapVolumeNode. Use the smallest necessary pixel size that can store the inside and outside values: unsigned char, signed char, unsigned short, short.

**Comment by fedorov** [comment]
> Use the smallest necessary pixel size that can store the inside and outside values: unsigned char, signed char, unsigned short, short.

Why not always use short, which is the pixel size used by the legacy Editor for label maps?

**Comment by lassoan** [comment]
If you only need to store 0 and 1 in a vtkImageData then there is no need for storing it on a short (2x more memory usage than char). Not a big deal, though. So, if any module that you need to use is hardcoded to use short (I hope there is no module like that) then it's fine to always use short.

**Comment by fedorov** [comment]
I understand the memory usage part, but I suggest consistency with the scalar type used for this node type by legacy Editor and during LabelMap "Add data" data load over miniscule memory savings.

**Comment by lassoan** [comment]
If you think there is any risk using char then feel free to use any other data type. I don't know about any module that would only work with short pixel type and not with char (except a few old editor effects). Also, users may load char labelmaps, so everything should work well with char labelmaps anyway.

**Comment by fedorov** [comment]
Sure, it's not a big deal for me - let's go with your suggestion.
