### ISSUE TITLE
Fix deprecated methods warnings

### ISSUE THREAD

**Issue by jamesobutler** [lassoan/SlicerSegmentEditorExtraEffects#21]
## Deprecated Warnings
```log
Warning: In C:\Slicer\Libs\MRML\Core\vtkMRMLDisplayNode.cxx, line 1140
vtkMRMLModelDisplayNode (000001C8006E8970): Deprecated, please use Visibility2DOn instead
```

https://github.com/lassoan/SlicerSegmentEditorExtraEffects/blob/ced238ec9b945246205f2d30865b138048f41057/SegmentEditorDrawTube/SegmentEditorDrawTubeLib/SegmentEditorEffect.py#L404-L409

https://github.com/lassoan/SlicerSegmentEditorExtraEffects/blob/ced238ec9b945246205f2d30865b138048f41057/SegmentEditorSurfaceCut/SegmentEditorSurfaceCutLib/SegmentEditorEffect.py#L374-L379

## Solution
If I use, `Visibility2DOn` instead of the deprecated method `SliceIntersectionVisibilityOn`, should this be accomplished with statements like 
```python
if slicer.app.mainApplicationMajorVersion >= 5 or (slicer.app.mainApplicationMajorVersion == 4 and slicer.app.mainApplicationMinorVersion >= 11):
  modelDisplayNode.Visibility2DOn() 
else:
  modelDisplayNode.SliceIntersectionVisibilityOn() 
```
or do you want to create a "4.10" branch for this repo?

**Comment by jamesobutler** [comment]
@lassoan Thoughts on this?

**Comment by lassoan** [comment]
Fix by checking the app version. It is not worth creating a new branch to manage this simple API change. Thank you!

**Comment by jamesobutler** [comment]
Will do! Thanks for the guidance
