### ISSUE TITLE
Split Segments doesn't fill correctly with signed data

### ISSUE THREAD

**Issue by muratmaga** [lassoan/SlicerSegmentEditorExtraEffects#32]
I have a dataset with -1024,3071 range. When I use the Split segment and specify the Fill value as -1024, it still pads with 0. 

Mask segment works correctly for the same dataset. My dataset is a bit big so I couldn't upload it. 
@smrolfe

**Comment by lassoan** [comment]
This issue has been fixed (there was a related commit and I cannot reproduce the problem).
