### ISSUE TITLE
Install on 4.11.20210226

### ISSUE THREAD

**Issue by liamtimms** [lassoan/SlicerSegmentEditorExtraEffects#39]
Hi,

Just wondering if there's plans to port this extension over to the latest Slicer. I'm not currently able to find it through the extension manager and I'm wondering how to best install it or whether I should jump back to a previous version of Slicer to continue using it. 

Thanks for all your incredible work.

**Comment by lassoan** [comment]
SegmentEditorExtraEffects is available for latest Slicer. See this page for more information: https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#extension-is-not-found-for-current-slicer-version
