### ISSUE TITLE
Engrave effect not working with current Slicer Preview 2021-08-12

### ISSUE THREAD

**Issue by Connor-Bowley** [lassoan/SlicerSegmentEditorExtraEffects#41]
The engrave effect is referencing a function `vtkMRMLMarkupsPlaneNode.GetPlaneToWorldMatrix` which no longer exists. It seems that it was changed to `vtkMRMLMarkupsPlaneNode.GetObjectToWorldMatrix` as part of https://github.com/Slicer/Slicer/commit/4c170cd7527a1cd2c1360d89d0fa6e54779064ad. Need to update to use new function.

**Comment by lassoan** [comment]
Good catch! Could you please send a pull request with the proposed change? Thank you!

**Comment by Connor-Bowley** [comment]
Here a PR that makes the functionality usable again. Note there is still an issue with edit button.

https://github.com/lassoan/SlicerSegmentEditorExtraEffects/pull/42
