### ISSUE TITLE
Draw tube effect bug

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerSegmentEditorExtraEffects#55]
Hi

I noticed that after drawing the first tube and clicking "Apply" and then drawing another tube and clicking "Apply" (on the same segment), the first tube is erased

Happens on:
- Slicer 5.4.0
- Slicer-5.5.0-2023-09-13-linux-amd64

**Comment by lassoan** [comment]
Each segment contains one tube. This is not a limitation but a feature, because this allows editing of the tube. If you want to add a new tube then you can click "Add segment".

**Comment by mauigna06** [comment]
> Each segment contains one tube. This is not a limitation but a feature, because this allows editing of the tube. If you want to add a new tube then you can click "Add segment".

Oh ok, I did not know how it worked. This is the only instruction I found:

https://github.com/lassoan/SlicerSegmentEditorExtraEffects/blob/f43df35af66a0b60000b008e0fa061d53319dc78/SegmentEditorDrawTube/SegmentEditorDrawTubeLib/SegmentEditorEffect.py#L41-L43

**Comment by lassoan** [comment]
No problem. If you have a suggestion for improving the help text then feel free to send a pull request. Thank you!
