### ISSUE TITLE
Threshold tool name

### ISSUE THREAD

**Issue by sedghi** [lassoan/SlicerSegmentEditorExtraEffects#59]
The extra effects feature appears to have a threshold tool named `threshodl`. However, I was unable to find an apply button. A suggestion would be to rename it to "Threshold Preview" or something similar for better clarity.

![CleanShot 2024-05-03 at 14 06 55@2x](https://github.com/lassoan/SlicerSegmentEditorExtraEffects/assets/7490180/31612dfc-7a16-4cf5-8007-53ce0b810ad5)
![CleanShot 2024-05-03 at 14 07 09@2x](https://github.com/lassoan/SlicerSegmentEditorExtraEffects/assets/7490180/a612e40c-814d-4647-974d-da981a98cd25)

**Comment by Sunderlandkyl** [comment]
Thanks @sedghi, the title should've been set to "Local threshold". Updated in https://github.com/lassoan/SlicerSegmentEditorExtraEffects/commit/73432418d98810dbe2c1195d0365b46e9fe23d9f.
